---
- name: Debug preferences server address
  debug: msg="preferences variable has value {{ flow_manager_preferences_server_host_address }} "

- name: Update the cloudBased.production config file's Preference Server address
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/configs/cloudBased.production.json"
    regexp: 'PREFERENCES_SERVER_URL'
    replace: '{{ flow_manager_preferences_server_host_address }}'
  notify: Restart the application systemd unit

- name: Update flowManager/configs/cloudBased.development.all.local.json config file's Preference Server address
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/flowManager/configs/cloudBased.development.all.local.json"
    regexp: 'PREFERENCES_SERVER_URL/preferences'
    replace: '{{ flow_manager_preferences_server_host_address }}/preferences'
  notify: Restart the application systemd unit
